# Generated by Django 3.2 on 2022-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('nota', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
