# Generated by Django 3.2 on 2022-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_2', '0002_category_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kiko',
            field=models.IntegerField(default=10),
        ),
    ]
