# Generated by Django 3.2 on 2022-08-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_2', '0003_category_kiko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kiko',
        ),
    ]
